### ISSUE TITLE
Multi-stage cluster addons: Rename helmChartName to name in clusteraddon.yaml

### ISSUE THREAD

**Issue by aniruddha2000** [SovereignCloudStack/cluster-stack-operator#200] opened 2024-06-14 09:54 UTC
/kind feature

**Describe the solution you'd like**
We name the stage "helmChartName" currently, even though it is not the helm chart name at all, but rather the name of the folder where the helm chart is inside. We should therefore rename the key in clusteraddon.yaml from "helmChartName" to "name".

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-stack-operator version:
- Kubernetes version: (use `kubectl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by janiskemper** [comment] 2024-06-14 09:57
duplicate of #199

**Closed by janiskemper** 2024-06-14 09:57 UTC
